music/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path

from music import views

app_name = 'music'

urlpatterns = [
    path('create_album/', login_required(views.AlbumCreate.as_view()), name='album_create'),
    path('create_singer/', login_required(views.SingerCreate.as_view()), name='singer_create'),
    path('create_song/', login_required(views.SongCreate.as_view()), name='song_create'),
    path('add_song/', views.add_song, name='add-song'),
    path('singer/<int:id>/', views.SingerDetailView.as_view(), name='singer_detail'),
    re_path(r'^song/(?P<pk>[0-9]+)/', views.SongDetailView.as_view(), name='song_detail'),
    re_path(r'^album/(?P<pk>[0-9]+)/', views.AlbumDetailView.as_view(), name='album_detail'),
    path('', views.song_list, name='song_list'),
    path('<slug:genre_slug>/', views.song_list, name='song_list_by_genre'),
]

twitter/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from rest_framework.routers import DefaultRouter
from .yasg import urlpatterns as doc_urls
from music.api import *
from account import views

router = DefaultRouter()
router.register('songs', APISongViewSet)
router.register('albums', APIAlbumViewSet)
router.register('singers', APISingerViewSet)
router.register('genres', APIGenreViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('tweets/', include('tweets.urls', namespace='tweets')),
    path('music/', include('music.urls', namespace='music')),
    path('api/v1/', include(router.urls)),
    path('', views.main),
]

urlpatterns += doc_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from common.validators import validate_file_extension


class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name='Genre name', unique=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        verbose_name_plural = 'Genres'
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('music:song_list_by_genre', args=[self.slug])


class Singer(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    image = models.ImageField(upload_to="images/singers", null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Singers'
        ordering = ['name', ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('music:singer_detail', args=[self.id, ])


class Album(models.Model):
    title = models.CharField(max_length=100, verbose_name='Album title', db_index=True)
    image = models.ImageField(upload_to="images/albums", null=True, blank=True)
    author = models.ForeignKey(Singer, on_delete=models.CASCADE, related_name='albums', related_query_name='album')
    published = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('music:album_detail', args=[self.id])

    class Meta:
        verbose_name_plural = 'Albums'
        ordering = ['-published', 'author', 'title']
        get_latest_by = 'published'


class Song(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    image = models.ImageField(upload_to="images/songs", null=True, blank=True)
    album = models.ForeignKey(Album, on_delete=models.SET_NULL, null=True, blank=True, related_query_name='songs',
                              related_name='songs')
    track = models.FileField(upload_to='songs/%Y/%m/%d', validators=[validate_file_extension])
    published = models.DateField(null=True, blank=True)
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True, blank=True, related_name='songs',
                              related_query_name='songs')
    singers = models.ManyToManyField(Singer, related_name='songs')
    clip_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('music:song_detail', args=[self.id])

    class Meta:
        verbose_name_plural = 'Songs'
        ordering = ['-published', 'title']
        get_latest_by = 'published'


class TrackUser(models.Model):
    user = models.ForeignKey('auth.User',
                             related_name='tracks_set',
                             related_query_name='tracks_set',
                             on_delete=models.CASCADE)
    track = models.ForeignKey(Song,
                              related_name='owners_set',
                              related_query_name='owners_set',
                              on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True,
                                 db_index=True)

    class Meta:
        ordering = ('added',)


User.add_to_class('tracks',
                  models.ManyToManyField(Song,
                                         through=TrackUser,
                                         related_name='owners',
                                         related_query_name='owners',
                                         blank=True, ))

music/forms.py
from django import forms

from common.validators import validate_file_extension
from music.models import Album, Singer, Song


class SongForm(forms.ModelForm):
    track = forms.FileField(validators=[validate_file_extension], label='Файл с треком')
    published = forms.DateField(required=False,
                                label='Дата публикации',
                                help_text='В формате YYYY-mm-dd')

    class Meta:
        model = Song
        widgets = {
            'genre': forms.RadioSelect,
        }
        fields = ('title', 'track', 'singers', 'image', 'album', 'published', 'genre', 'clip_link')


class SingerForm(forms.ModelForm):
    class Meta:
        model = Singer
        fields = ('name', 'image',)


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ('title', 'image', 'author', 'published')

music/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q, F
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DetailView, ListView

from account.models import Profile
from common.decorators import ajax_required
from music.forms import AlbumForm, SingerForm, SongForm
from music.models import Album, Singer, Song, Genre, TrackUser


class AlbumCreate(CreateView):
    form_class = AlbumForm
    model = Album
    template_name = 'music/album_create.html'

    def get_success_url(self):
        return reverse('dashboard')


class SingerCreate(CreateView):
    form_class = SingerForm
    model = Singer
    template_name = 'music/singer_create.html'

    def get_success_url(self):
        return reverse('dashboard')


class SongCreate(CreateView):
    form_class = SongForm
    model = Song
    template_name = 'music/song_create.html'

    def get_success_url(self):
        return reverse('dashboard')


def song_list(request, genre_slug=None, ):
    genre = None
    genres = Genre.objects.all()
    songs = Song.objects.all()
    search_q = request.GET.get('q')
    if search_q:
        songs = songs.filter(Q(title__icontains=search_q) | Q(singers__name__icontains=search_q)).distinct()
    if genre_slug:
        genre = get_object_or_404(Genre, slug=genre_slug)
        songs = songs.filter(genre=genre)
    return render(request, 'music/song_list.html',
                  {'genre': genre,
                   'genres': genres,
                   'songs': songs,
                   'section': 'songs', })


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'music/album_detail.html'


class SingerDetailView(DetailView):
    model = Singer
    pk_url_kwarg = 'id'
    template_name = 'music/singer_detail.html'


# class AlbumListView(ListView):
#     template_name = 'music/album_list.html'
#     model = Album
#     context_object_name = 'albums'
#
#
# class SingerListView(ListView):
#     template_name = 'music/singer_list.html'
#     model = Singer
#     context_object_name = 'singers'


class SongDetailView(DetailView):
    model = Song
    template_name = 'music/song_detail.html'


@ajax_required
@login_required
@require_POST
def add_song(request):
    song_id = request.POST.get('id')
    action = request.POST.get('action')
    cur_user = request.user
    if song_id and action:
        try:
            song = Song.objects.get(id=song_id)
            if action == 'add':
                TrackUser.objects.get_or_create(user=request.user,
                                                track=song)
                Profile.objects.filter(user=cur_user).update(track_counts=F('track_counts') + 1)

            else:
                TrackUser.objects.filter(user=request.user,
                                         track=song).delete()
                Profile.objects.filter(user=cur_user).update(track_counts=F('track_counts') - 1)
            return JsonResponse({'status': 'ok', })
        except Song.DoesNotExist:
            return JsonResponse({'status': 'ok', })
    return JsonResponse({'status': 'ok'})

music/templates/music/album_create.html
{% extends 'base.html' %}

{% block title %}Добавить альбом{% endblock %}

{% block content %}
    <h1>Добавить альбом</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

music/templates/music/album_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Альбом {{ album.title }}
{% endblock %}

{% block content %}
    <h1>{{ album.title }}</h1>
    <div class="row">
        <p>Опубликовано: {{ album.published|date:"d F Y" }}</p>
        <img src="{% if album.image %}{{ album.image.url }}{% else %}
                            {% static "img/no_album_image.jpg" %}{% endif %}"
             class="user-detail" width="200px" height="200px">
        <p>Автор: <a href="{{ album.author.get_absolute_url }}">{{ album.author.name }}</a></p>
        <hr>

    </div>
<h2>Музыка</h2>
    <div class="row">
    <div class="col-12">
        {% for song in album.songs.all %}
            {% include 'music/song_part.html' with song=song %}
        {% empty %}
            Ничего не найдено
        {% endfor %}
    </div>

    </div>
{% endblock %}

music/templates/music/album_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

music/templates/music/singer_create.html
{% extends 'base.html' %}

{% block title %}Добавить исполнителя{% endblock %}

{% block content %}
    <h1>Добавить исполнителя</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

music/templates/music/singer_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ singer.name }}
{% endblock %}

{% block content %}
    <h1>{{ singer.name }}</h1>
    <div class="row">
        <div class="col-3">
            <img src="{% if singer.image %}{{ singer.image.url }}{% else %}
                            {% static "img/no_album_image.jpg" %}{% endif %}"
                 class="user-detail" width="200px" height="200px">
        </div>
        <div class="col">
            <h3>Альбомы:</h3>
            <ul>
                {% for album in singer.albums.all %}
                    <li><a href="{{ album.get_absolute_url }}">{{ album.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <hr>
    <div class="row">
        <h2>Треки</h2>
        <div class="col-12">
            {% for song in songs %}
                {% include 'music/song_part.html' with song=song %}
            {% empty %}
                Ничего не найдено
            {% endfor %}
        </div>

    </div>


{% endblock %}

music/templates/music/singer_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

music/templates/music/song_create.html
{% extends 'base.html' %}

{% block title %}Добавить трек{% endblock %}

{% block content %}
    <h1>Добавить трек</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

music/templates/music/song_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ song.title }}
{% endblock %}

{% block content %}
    <h1>{{ song.title }}</h1>
    <div class="row">
        <div class="col-4">
            <img src="{% if song.image %}{{ song.image.url }}{% else %}
                            {% static "img/no_song_image.png" %}{% endif %}"
                 class="user-detail" width="200px" height="200px">
        </div>
        <div class="col-8">
            <p>
                Исполнители:
                <span>
                        {% for singer in song.singers.all %}
                            <a href="{{ singer.get_absolute_url }}">{{ singer.name }}</a>
                        {% endfor %}
                    </span>
            </p>
            <p>
                Опубликовано: {{ song.published|date:"d-m-Y" }}
            </p>
            <p>
                Жанр: {{ song.genre.name }}
            </p>
            <p>
                {% if song.album %}
                    Альбом: <a href="{{ song.album.get_absolute_url }}">{{ song.album.title }}</a>
                {% else %}
                    СИНГЛ
                {% endif %}
            </p>
        </div>
    </div>
    <div class="row">
        <audio controls style="width: 100%">
            <source src="{{ song.track.url }}" type="audio/ogg">
            Your browser dose not Support the audio Tag
        </audio>
    </div>
    <div class="row">

    </div>

    {% if song.clip_link %}
        <iframe width="560" height="315" src="{{ song.clip_link }}" frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
    {% endif %}

{% endblock %}

music/templates/music/song_list.html
{% extends 'base.html' %}

{% block title %}
    Треки
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-10">
            <form action="" method="get">
                <input type="text" placeholder="Поиск" name="q">
                <button type="submit" class="btn btn-primary">Найти</button>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-2">
            <h3>Жанры</h3>
            <ul style="list-style-type: none">
                <li class="">
                    <a class="{% if not genre %}text-danger{% endif %}" href="{% url "music:song_list" %}">Все</a>
                </li>
                {% for g in genres %}
                    <li class="">
                        <a class="{% if g.slug == genre.slug %}text-danger{% endif %}"
                           href="{{ g.get_absolute_url }}">{{ g.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-10">
            <h1 class="mb-2">Музыка</h1>
            <br>
            <div class="container mt-2">
                {% for song in songs %}
                    {% include 'music/song_part.html' with song=song %}
                {% empty %}
                    Ничего не найдено
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block domready %}
    $('a.track').click(function(e){
        var _this=this;
        e.preventDefault();
        $.post(
            '{% url "music:add-song" %}',
            { id: $(this).data('id'), action: $(this).data('action')},
            function(data){
                if (data['status']=='ok'){
                    var previous_action = $(_this).data('action');
                    // Изменяем переменную действия.
                    $(_this).data('action', previous_action == 'add' ?'delete' : 'add');
                    // Изменяем текст ссылки.
                    $(_this).text(previous_action == 'add' ?'-' : '+');
                }
            }
        );
    });
{% endblock %}

music/templates/music/song_part.html
{% load static %}

<div>
    <div class="row my-1">
        <div class="col-1">
            <img src="{% if song.image %}{{ song.image.url }}{% else %}
                                            {% static "img/no_song_image.png" %}{% endif %}"
                 alt=""
                 height="80px"
                 width="80px"
                 class="z-depth-1"
                 style="object-fit: cover;">
        </div>
        <div class="col-4">
            <h6 class=""><a href="{{ song.get_absolute_url }}">{{ song.title }}</a>
            </h6>
            <span>{% for singer in song.singers.all %}
                <a href="{{ singer.get_absolute_url }}">{{ singer.name }}</a>{% endfor %}
                                </span>
        </div>
        <div class="col">
            <audio controls>
                <source src="{{ song.track.url }}"/>
            </audio>
        </div>
    {% if request.user.is_authenticated %}
        <div class="col-1">
            <a href="#"
               id="track{{ song.id }}"
               data-id="{{ song.id }}"
               data-action="{% if song in request.user.tracks.all %}delete{% else %}add{% endif %}"
               class="track">
                {% if song in request.user.tracks.all %}-{% else %}+{% endif %}
            </a>
        </div>
    {% endif %}
    </div>
    <hr/>
</div>