music/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path

from music import views

app_name = 'music'

urlpatterns = [
    path('create_album/', login_required(views.AlbumCreate.as_view()), name='album_create'),
    path('create_singer/', login_required(views.SingerCreate.as_view()), name='singer_create'),
    path('create_song/', login_required(views.SongCreate.as_view()), name='song_create'),
    path('add_song/', views.add_song, name='add-song'),
    path('singer/<int:id>/', views.SingerDetailView.as_view(), name='singer_detail'),
    re_path(r'^song/(?P<pk>[0-9]+)/', views.SongDetailView.as_view(), name='song_detail'),
    re_path(r'^album/(?P<pk>[0-9]+)/', views.AlbumDetailView.as_view(), name='album_detail'),
    path('', views.song_list, name='song_list'),
    path('<slug:genre_slug>/', views.song_list, name='song_list_by_genre'),
]

tweets/urls.py
from django.urls import path
from tweets import views

app_name = 'tweets'

urlpatterns = [
    path('create/', views.tweet_create, name='create'),
    path('detail/<int:id>/', views.tweet_detail, name='detail'),
    path('', views.tweet_list, name='list'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('reply/<int:id>/', views.add_reply, name='reply'),
    path('like/<int:pk>/', views.like, name='like'),
    path('dislike/<int:pk>/', views.dislike, name='dislike'),
]

twitter/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from rest_framework.routers import DefaultRouter
from .yasg import urlpatterns as doc_urls
from music.api import *
from account import views

router = DefaultRouter()
router.register('songs', APISongViewSet)
router.register('albums', APIAlbumViewSet)
router.register('singers', APISingerViewSet)
router.register('genres', APIGenreViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('tweets/', include('tweets.urls', namespace='tweets')),
    path('music/', include('music.urls', namespace='music')),
    path('api/v1/', include(router.urls)),
    path('', views.main),
]

urlpatterns += doc_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweets/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.text import slugify


class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='tweets_created',
                             on_delete=models.CASCADE)
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True, blank=True, db_index=True)
    reply_to = models.ForeignKey("Tweet",
                                 related_name="replies",
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank=True)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('tweets:detail', args=[self.id, ])


class Like(models.Model):
    post = models.ForeignKey(Tweet, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='likes')

    class Meta:
        unique_together = (('post', 'user'),)

    def __str__(self):
        return self.post.text + ': ' + self.user.username


class Dislike(models.Model):
    post = models.ForeignKey(Tweet, on_delete=models.CASCADE, related_name='dislikes')
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='dislikes')

    class Meta:
        unique_together = (('post', 'user'),)

    def __str__(self):
        return self.post.text + ': ' + self.user.username

tweets/forms.py
from django import forms
from django.utils.text import slugify

from .models import Tweet


class TweetForm(forms.ModelForm):
    text = forms.CharField(required=True,
                           widget=forms.widgets.Textarea())

    class Meta:
        model = Tweet
        exclude = ('user', 'reply_to',)

tweets/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy

from tweets.forms import TweetForm
from tweets.models import Tweet, Like, Dislike


@login_required
def tweet_create(request):
    if request.method == 'POST':
        tweet_form = TweetForm(request.POST)
        if tweet_form.is_valid():
            Tweet.objects.create(text=tweet_form.cleaned_data['text'], user=request.user)
            messages.success(request, 'Tвит добавлен успешно')
            return HttpResponseRedirect(reverse('dashboard'))
    else:
        tweet_form = TweetForm()
    return render(request, 'tweets/tweet/create.html', {'tweet_form': tweet_form})


def tweet_detail(request, id):
    tweet = get_object_or_404(Tweet, id=id)
    return render(request,
                  'tweets/tweet/detail.html',
                  {'section': 'tweets',
                   'tweet': tweet, })


@login_required
def tweet_list(request):
    tweets = Tweet.objects.order_by('-pub_date').all()
    if request.is_ajax():
        return render(request,
                      'tweets/tweet/list_ajax.html',
                      {'section': 'tweets',
                       'tweets': tweets})
    return render(request,
                  'tweets/tweet/list.html',
                  {'section': 'tweets',
                   'tweets': tweets})


@login_required
def delete(request, id):
    try:
        person = Tweet.objects.get(id=id)
        person.delete()
        return HttpResponseRedirect(reverse('dashboard'))
    except Tweet.DoesNotExist:
        return HttpResponse("Нет такого поста")


@login_required
def add_reply(request, id):
    if request.method == 'POST':
        tweet_form = TweetForm(request.POST)
        if tweet_form.is_valid():
            Tweet.objects.create(text=tweet_form.cleaned_data['text'],
                                 user=request.user,
                                 reply_to=Tweet.objects.get(id=id))
            messages.success(request, 'Комент добавлен успешно')
            return HttpResponseRedirect(reverse('dashboard'))
    else:
        tweet_form = TweetForm()
    return render(request, 'tweets/tweet/create.html', {'tweet_form': tweet_form})


@login_required
def like(request, pk):
    if Like.objects.filter(post_id=pk, user=request.user).exists():
        Like.objects.get(post_id=pk, user=request.user).delete()
    else:
        if Dislike.objects.filter(post_id=pk, user=request.user).exists():
            Dislike.objects.get(post_id=pk, user=request.user).delete()
        Like.objects.create(post_id=pk, user=request.user)
    return redirect('tweets:detail', pk)


@login_required
def dislike(request, pk):
    if Dislike.objects.filter(post_id=pk, user=request.user).exists():
        Dislike.objects.get(post_id=pk, user=request.user).delete()
    else:
        if Like.objects.filter(post_id=pk, user=request.user).exists():
            Like.objects.get(post_id=pk, user=request.user).delete()
        Dislike.objects.create(post_id=pk, user=request.user)
    return redirect('tweets:detail', pk)

tweets/templates/tweets/tweet/create.html
{% extends "base.html" %}

{% block title %}Добавить твит{% endblock %}

{% block content %}
    <h1>Добавить твит</h1>
    <form action="." method="post">
        {{ tweet_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Отправить">
    </form>
{% endblock %}

tweets/templates/tweets/tweet/detail.html
{% extends "base.html" %}

{% block title %}Твиты{% endblock %}

{% block content %}
    <a href="{{ tweet.user.get_absolute_url }}">
        <img src="{{ tweet.user.profile.photo.url }}" alt="{{ tweet.user.get_full_name }}" class="user-detail"
             width="80px" height="80px">
        <h1 class="tweet-detail">{{ tweet.user }}</h1>
    </a>
    <div class="tweet">
        <i>{{ tweet.pub_date }}</i>
        <p>{{ tweet.text|linebreaks }}</p>
        <a href="{% url 'tweets:like' tweet.id %}" class="btn btn-success">Like</a>
        <a href="{% url 'tweets:dislike' tweet.id %}" class="btn btn-danger">DisLike</a>
        <br>
        <p><b>Лайки: {{ tweet.likes.count }}</b> <b>Дизлайки: {{ tweet.dislikes.count }}</b></p>
        <a href="{% url 'tweets:reply' tweet.id %}">Ответить</a>
    </div>
    {% for reply in tweet.replies.all %}
        <div class="tweet" style="margin-left: 10%">
            <img src="{{ reply.user.profile.photo.url }}" alt="{{ reply.user.get_full_name }}">
            <a href="{{ reply.user.get_absolute_url }}"><span>{{ reply.user.get_full_name }}</span></a>
            <i>{{ reply.pub_date }}</i>
            {% if reply.user == request.user %}
                <a href="{% url 'tweets:delete' reply.id %}"><span class="close"></span></a>
            {% endif %}
            <a href="{% url 'tweets:detail' reply.id %}" class="none-style-a"><p>{{ reply.text }}</p></a>
        </div>
    {% endfor %}
{% endblock %}

tweets/templates/tweets/tweet/list.html
{% extends "base.html" %}

{% block title %}Лента твитов{% endblock %}

{% block content %}
    <h1>Лента</h1>
    <div class="tweets">
        {% include "tweets/tweet/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
     block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
       if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#image-list').append(data);
        }
      });
    }
  });
{% endblock %}

tweets/templates/tweets/tweet/list_ajax.html
{% if not request.user.following.all %}
    <a href="{% url 'user_list' %}">Подпишитесь на людей, чтобы видеть их твиты</a>
{% endif %}


{% for tweet in tweets %}
    {% if not tweet.reply_to and tweet.user in request.user.following.all or tweet.user == request.user and not tweet.reply_to %}
        <div class="tweet" id="{{ tweet.id }}">
            <img src="{{ tweet.user.profile.photo.url }}" alt="{{ tweet.user.get_full_name }}">
            <a href="{{ tweet.user.get_absolute_url }}"><span>{{ tweet.user.get_full_name }}</span></a>
            <i>{{ tweet.pub_date }}</i>
            {% if tweet.user == request.user %}
                <a href="{% url 'tweets:delete' tweet.id %}"><span class="close"></span></a>
            {% endif %}

            <a href="{% url 'tweets:detail' tweet.id %}" class="none-style-a"><p>{{ tweet.text }}</p></a>
            <a href="{% url 'tweets:reply' tweet.id %}">Ответить</a>
            <a href="{% url 'tweets:like' tweet.id %}" class="btn btn-success">Like</a>
            <a href="{% url 'tweets:dislike' tweet.id %}" class="btn btn-danger">DisLike</a>
            <br>
            <p><b>Лайки: {{ tweet.likes.count }}</b> <b>Дизлайки: {{ tweet.dislikes.count }}</b></p>

        </div>
        {% for reply in tweet.replies.all %}
            <div class="tweet" style="margin-left: 10%">
                <img src="{{ reply.user.profile.photo.url }}" alt="{{ reply.user.get_full_name }}">
                <a href="{{ reply.user.get_absolute_url }}"><span>{{ reply.user.get_full_name }}</span></a>
                <i>{{ reply.pub_date }}</i>
                <a href="#{{ reply.reply_to.id }}">&gt;&gt;&gt;{{ reply.reply_to.id }}</a>
                {% if reply.user == request.user %}
                    <a href="{% url 'tweets:delete' reply.id %}"><span class="close"></span></a>
                {% endif %}
                <a href="{% url 'tweets:detail' reply.id %}" class="none-style-a"><p>{{ reply.text }}</p></a>
            </div>
        {% endfor %}
    {% endif %}
{% endfor %}